a = int(input('Enter the value of a = '))
b = int (input('Enter the value of b = '))
print("The sum of a and b is:",a+b)
print("The subtraction of a and b is :",a-b)
print("The multiplication of a and b is :",a*b)
print("The divide of a and b is :",a/b)
print(type(a))
print(type(b))